### PR TITLE
Just some optimize

### PR DESCRIPTION
**Pull request by Piterden**
Checked - works

### CODE REVIEW

**Comment by fryiee** [comment]
My only concern with this is that we should really change the base class to .select2-{field_type} to prevent multiple instantiation when we have it on multiple field types.

**Comment by Piterden** [comment]
Absent of `!$(element).hasClass('select2-hidden-accessible')` not calls any errors for me with multiple selects in form.
image
Are you sure that select2 haven't its own internal avoiding that problem mechanism?
For example from there https://addyosmani.com/resources/essentialjsdesignpatterns/book

**Comment by fryiee** [comment]
Sorry I meant when we introduce select2 into multiple field types (which is what Ryan / myself are doing currently) it will instantiate again if we leave it as the basic .select2 as they will both have JS assets that initialise

**Comment by RyanThompson** [comment]
Outdated

**Comment by Piterden** [comment]
That's better? @fryiee

**Comment by RyanThompson** [comment]
This should be good now - update!

**Pull request closed without merging**
